select CONSTRAINT_CATALOG,
       CONSTRAINT_SCHEMA,
       CONSTRAINT_NAME,
       TABLE_CATALOG,
       TABLE_SCHEMA,
       TABLE_NAME,
       COLUMN_NAME,
       ORDINAL_POSITION,
       POSITION_IN_UNIQUE_CONSTRAINT,
       REFERENCED_TABLE_SCHEMA,
       REFERENCED_TABLE_NAME,
       REFERENCED_COLUMN_NAME
from information_schema.KEY_COLUMN_USAGE
where TABLE_SCHEMA = ?