<div>
    <button type="button" class="btn btn-success btn-lg" ng-click="diff()">对比</button>
    <button type="button" class="btn btn-danger btn-lg" ng-click="update()">更新</button>
</div>
<div>
    <button type="button" class="btn btn-success btn-lg" ng-click="showLeftSql()">查看<-SQL</button>
    <button type="button" class="btn btn-success btn-lg" ng-click="showRightSql()">查看->SQL</button>
    <button type="button" class="btn btn-success btn-lg" ng-click="exportDifference()">导出差异SQL</button>
</div>
